// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SklepPB.DAL;

#nullable disable

namespace SklepPB.Migrations
{
    [DbContext(typeof(FilmsContext))]
    [Migration("20260408063157_Poster")]
    partial class Poster
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SklepPB.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Film akcji",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Komedia",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "Film dramatyczny",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Desc = "Straszny film",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            Desc = "Film science fiction",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 6,
                            Desc = "Film romantyczny",
                            Name = "Romance"
                        });
                });

            modelBuilder.Entity("SklepPB.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            Desc = "Film o snach",
                            Director = "Christopher Nolan",
                            Poster = "1.png",
                            Price = 19.99m,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Desc = "Film o Batmanie",
                            Director = "Christopher Nolan",
                            Poster = "2.png",
                            Price = 14.99m,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Desc = "Historia życia Forresta Gumpa",
                            Director = "Robert Zemeckis",
                            Poster = "3.png",
                            Price = 9.99m,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Desc = "Film o duchach",
                            Director = "James Wan",
                            Poster = "4.png",
                            Price = 12.99m,
                            Title = "The Conjuring"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Desc = "Komedia o wieczorze kawalerskim",
                            Director = "Todd Phillips",
                            Poster = "5.png",
                            Price = 8.99m,
                            Title = "The Hangover"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Desc = "Film o katastrofie Titanica",
                            Director = "James Cameron",
                            Poster = "6.png",
                            Price = 11.99m,
                            Title = "Titanic"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Desc = "Film o wirtualnej rzeczywistości",
                            Director = "The Wachowskis",
                            Poster = "7.png",
                            Price = 15.99m,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Desc = "Film o rzymskim gladiatorze",
                            Director = "Ridley Scott",
                            Poster = "8.png",
                            Price = 13.99m,
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Desc = "Film o więzieniu Shawshank",
                            Director = "Frank Darabont",
                            Poster = "9.png",
                            Price = 10.99m,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Desc = "Horror o rasizmie",
                            Director = "Jordan Peele",
                            Poster = "10.png",
                            Price = 9.99m,
                            Title = "Get Out"
                        });
                });

            modelBuilder.Entity("SklepPB.Models.Film", b =>
                {
                    b.HasOne("SklepPB.Models.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SklepPB.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
