// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SklepPB.DAL;

#nullable disable

namespace SklepPB.Migrations
{
    [DbContext(typeof(FilmsContext))]
    partial class FilmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SklepPB.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Film akcji",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Komedia",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "Film dramatyczny",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Desc = "Straszny film",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            Desc = "Film science fiction",
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 6,
                            Desc = "Film romantyczny",
                            Name = "Romance"
                        });
                });

            modelBuilder.Entity("SklepPB.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            Desc = "Film o snach",
                            Director = "Christopher Nolan",
                            Poster = "1.png",
                            Price = 19.99m,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Desc = "Film o Batmanie",
                            Director = "Christopher Nolan",
                            Poster = "2.png",
                            Price = 14.99m,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Desc = "Historia życia Forresta Gumpa",
                            Director = "Robert Zemeckis",
                            Poster = "3.png",
                            Price = 9.99m,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Desc = "Film o duchach",
                            Director = "James Wan",
                            Poster = "4.png",
                            Price = 12.99m,
                            Title = "The Conjuring"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Desc = "Komedia o wieczorze kawalerskim",
                            Director = "Todd Phillips",
                            Poster = "5.png",
                            Price = 8.99m,
                            Title = "The Hangover"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Desc = "Film o katastrofie Titanica",
                            Director = "James Cameron",
                            Poster = "6.png",
                            Price = 11.99m,
                            Title = "Titanic"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Desc = "Film o wirtualnej rzeczywistości",
                            Director = "The Wachowskis",
                            Poster = "7.png",
                            Price = 15.99m,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Desc = "Film o rzymskim gladiatorze",
                            Director = "Ridley Scott",
                            Poster = "8.png",
                            Price = 13.99m,
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Desc = "Film o więzieniu Shawshank",
                            Director = "Frank Darabont",
                            Poster = "9.png",
                            Price = 10.99m,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Desc = "Horror o rasizmie",
                            Director = "Jordan Peele",
                            Poster = "10.png",
                            Price = 9.99m,
                            Title = "Get Out"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Desc = "Postapokaliptyczny pościg przez pustynię",
                            Director = "George Miller",
                            Price = 16.99m,
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Desc = "Były zabójca wraca do gry",
                            Director = "Chad Stahelski",
                            Price = 14.99m,
                            Title = "John Wick"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Desc = "Policjant kontra terroryści",
                            Director = "John McTiernan",
                            Price = 12.99m,
                            Title = "Die Hard"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Desc = "Superbohaterowie ratują świat",
                            Director = "Joss Whedon",
                            Price = 15.99m,
                            Title = "The Avengers"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Desc = "Agent Ethan Hunt w kolejnej misji",
                            Director = "Christopher McQuarrie",
                            Price = 17.99m,
                            Title = "Mission: Impossible – Fallout"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Desc = "Policyjny szturm na wieżowiec",
                            Director = "Gareth Evans",
                            Price = 11.99m,
                            Title = "The Raid"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Desc = "James Bond w nowej odsłonie",
                            Director = "Martin Campbell",
                            Price = 13.99m,
                            Title = "Casino Royale"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Desc = "Dwóch gliniarzy przeciw mafii",
                            Director = "Richard Donner",
                            Price = 10.99m,
                            Title = "Lethal Weapon"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Desc = "Powrót legendarnego pilota",
                            Director = "Joseph Kosinski",
                            Price = 18.99m,
                            Title = "Top Gun: Maverick"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Desc = "Bitwa pod Termopilami",
                            Director = "Zack Snyder",
                            Price = 9.99m,
                            Title = "300"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Desc = "Szkolna komedia o przyjaźni",
                            Director = "Greg Mottola",
                            Price = 9.99m,
                            Title = "Superbad"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Desc = "Dwóch dorosłych braci pod jednym dachem",
                            Director = "Adam McKay",
                            Price = 8.99m,
                            Title = "Step Brothers"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Desc = "Magiczna maska zmienia życie bohatera",
                            Director = "Chuck Russell",
                            Price = 7.99m,
                            Title = "The Mask"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Desc = "Chłopiec kontra włamywacze",
                            Director = "Chris Columbus",
                            Price = 10.99m,
                            Title = "Home Alone"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Desc = "Dwóch przyjaciół w podróży",
                            Director = "Peter Farrelly",
                            Price = 6.99m,
                            Title = "Dumb and Dumber"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Desc = "Ekscentryczna komedia hotelowa",
                            Director = "Wes Anderson",
                            Price = 11.99m,
                            Title = "The Grand Budapest Hotel"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            Desc = "Tajniacy w liceum",
                            Director = "Phil Lord & Christopher Miller",
                            Price = 9.49m,
                            Title = "21 Jump Street"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Desc = "Prezenter wiadomości w krzywym zwierciadle",
                            Director = "Adam McKay",
                            Price = 8.49m,
                            Title = "Anchorman"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Desc = "Senior stażystą w startupie",
                            Director = "Nancy Meyers",
                            Price = 10.49m,
                            Title = "The Intern"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Desc = "Druhenki w tarapatach",
                            Director = "Paul Feig",
                            Price = 9.49m,
                            Title = "Bridesmaids"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Desc = "Strażnik więzienny i niezwykły skazaniec",
                            Director = "Frank Darabont",
                            Price = 12.99m,
                            Title = "The Green Mile"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            Desc = "Podziemny klub walki",
                            Director = "David Fincher",
                            Price = 11.99m,
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Desc = "Historia mafijnej rodziny",
                            Director = "Francis Ford Coppola",
                            Price = 14.99m,
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            Desc = "Historia genialnego matematyka",
                            Director = "Ron Howard",
                            Price = 10.99m,
                            Title = "A Beautiful Mind"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 3,
                            Desc = "Ambicja młodego perkusisty",
                            Director = "Damien Chazelle",
                            Price = 9.99m,
                            Title = "Whiplash"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Desc = "Narodziny złoczyńcy",
                            Director = "Todd Phillips",
                            Price = 13.99m,
                            Title = "Joker"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            Desc = "Losy pianisty w czasie wojny",
                            Director = "Roman Polanski",
                            Price = 11.49m,
                            Title = "The Pianist"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 3,
                            Desc = "Konflikt dwóch rodzin",
                            Director = "Bong Joon-ho",
                            Price = 12.49m,
                            Title = "Parasite"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 3,
                            Desc = "Historia powstania Facebooka",
                            Director = "David Fincher",
                            Price = 10.49m,
                            Title = "The Social Network"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            Desc = "Historia bezwzględnego przedsiębiorcy",
                            Director = "Paul Thomas Anderson",
                            Price = 12.99m,
                            Title = "There Will Be Blood"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Desc = "Mroczna tajemnica rodziny",
                            Director = "Ari Aster",
                            Price = 11.99m,
                            Title = "Hereditary"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            Desc = "Dzieci kontra klaun",
                            Director = "Andy Muschietti",
                            Price = 10.99m,
                            Title = "It"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Desc = "Koszmar z Freddy'm",
                            Director = "Wes Craven",
                            Price = 8.99m,
                            Title = "A Nightmare on Elm Street"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            Desc = "Egzorcyzmy młodej dziewczyny",
                            Director = "William Friedkin",
                            Price = 9.99m,
                            Title = "The Exorcist"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            Desc = "Tajemnicza kaseta wideo",
                            Director = "Gore Verbinski",
                            Price = 8.49m,
                            Title = "The Ring"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Desc = "Potwór z dziecięcej książki",
                            Director = "Jennifer Kent",
                            Price = 7.99m,
                            Title = "The Babadook"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Desc = "Rodzina nawiedzana przez duchy",
                            Director = "James Wan",
                            Price = 9.49m,
                            Title = "Insidious"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Desc = "Pisarz odkrywa przerażające nagrania",
                            Director = "Scott Derrickson",
                            Price = 8.49m,
                            Title = "Sinister"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            Desc = "Rodzina w obliczu mrocznych sił",
                            Director = "Robert Eggers",
                            Price = 9.99m,
                            Title = "The Witch"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            Desc = "Niepokojący festiwal w Szwecji",
                            Director = "Ari Aster",
                            Price = 12.49m,
                            Title = "Midsommar"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 5,
                            Desc = "Podróż międzygwiezdna",
                            Director = "Christopher Nolan",
                            Price = 17.99m,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 5,
                            Desc = "Łowca androidów",
                            Director = "Denis Villeneuve",
                            Price = 14.99m,
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            Desc = "Kontakt z obcą cywilizacją",
                            Director = "Denis Villeneuve",
                            Price = 12.99m,
                            Title = "Arrival"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 5,
                            Desc = "Początek kosmicznej sagi",
                            Director = "George Lucas",
                            Price = 13.99m,
                            Title = "Star Wars: A New Hope"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 5,
                            Desc = "Cyborg z przyszłości",
                            Director = "James Cameron",
                            Price = 10.99m,
                            Title = "The Terminator"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 5,
                            Desc = "Konflikt na planecie Pandora",
                            Director = "James Cameron",
                            Price = 15.99m,
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 5,
                            Desc = "Eksperyment ze sztuczną inteligencją",
                            Director = "Alex Garland",
                            Price = 9.99m,
                            Title = "Ex Machina"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 5,
                            Desc = "Walka o pustynną planetę",
                            Director = "Denis Villeneuve",
                            Price = 16.99m,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 5,
                            Desc = "Pętla czasowa w wojnie z obcymi",
                            Director = "Doug Liman",
                            Price = 11.99m,
                            Title = "Edge of Tomorrow"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 5,
                            Desc = "Walka o przetrwanie w kosmosie",
                            Director = "Alfonso Cuarón",
                            Price = 10.99m,
                            Title = "Gravity"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 6,
                            Desc = "Romantyczna historia miłosna",
                            Director = "Nick Cassavetes",
                            Price = 9.99m,
                            Title = "The Notebook"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 6,
                            Desc = "Miłość i konwenanse",
                            Director = "Joe Wright",
                            Price = 8.99m,
                            Title = "Pride & Prejudice"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 6,
                            Desc = "Miłość i marzenia w Los Angeles",
                            Director = "Damien Chazelle",
                            Price = 12.99m,
                            Title = "La La Land"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 6,
                            Desc = "Romantyczna noc w Wiedniu",
                            Director = "Richard Linklater",
                            Price = 7.99m,
                            Title = "Before Sunrise"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 6,
                            Desc = "Miłość w trudnych okolicznościach",
                            Director = "Thea Sharrock",
                            Price = 8.49m,
                            Title = "Me Before You"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 6,
                            Desc = "Romans z gwiazdą filmową",
                            Director = "Roger Michell",
                            Price = 9.49m,
                            Title = "Notting Hill"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 6,
                            Desc = "Miłość i muzyka",
                            Director = "Bradley Cooper",
                            Price = 11.99m,
                            Title = "A Star Is Born"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 6,
                            Desc = "Miłość dwojga nastolatków",
                            Director = "Josh Boone",
                            Price = 8.99m,
                            Title = "The Fault in Our Stars"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 6,
                            Desc = "Miłosne perypetie kilku par",
                            Director = "Glenn Ficarra & John Requa",
                            Price = 9.99m,
                            Title = "Crazy, Stupid, Love"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 6,
                            Desc = "Kilka historii miłosnych",
                            Director = "Richard Curtis",
                            Price = 10.49m,
                            Title = "Love Actually"
                        });
                });

            modelBuilder.Entity("SklepPB.Models.Film", b =>
                {
                    b.HasOne("SklepPB.Models.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SklepPB.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
